HOST_IP = "127.0.0.1"

RABBIT_MQ_PORTS = {
    1: 5672,
    2: 5673,
    3: 5674
}
RABBIT_MQ_USER = "guest"
RABBIT_MQ_PASSWORD = "guest"
RABBIT_MQ_VIRTUAL_HOST = "/"

SUBSCRIPTIONS_QUEUE = "subs"
PUBLICATIONS_QUEUE = "pubs"
SUBSCRIPTIONS_COUNT = 2
PUBLICATIONS_COUNT = 1
